### ISSUE TITLE
Versione PHP

### ISSUE THREAD

**Issue by portapipe** [ChiarilloMassimo/satispay-php-sdk#3]
Ciao
Guzzle richiede php 5.5 e superiore.
Ti ho modificato il composer.json affinché richieda quella versione (io sono in php 5.3 con un cliente e mi ha dato errore guzzle, non la tua libreria)

**Comment by massimo-me** [comment]
Si effettivamente 👍 

Grazie

**Comment by portapipe** [comment]
Non c'è modo di averlo per php 5.3? Ci salverebbe tipo 4 giorni di lavoro...

**Comment by massimo-me** [comment]
@portapipe Mi dispiace, purtroppo non ha alcun senso essendo tutto basato su`guzzlehttp/guzzle` che non supporta la `5.3` dalla versione `3.*` sarebbe del lavoro inutile e fatto appositamente per voi. 

Secondo me se provate a cambiare versione di php nell'sdk officiale potrebbe funzionare https://github.com/satispay/online-api-php-sdk.

Ad ogni modo credo di continuare lo sviluppo a settembre ✌️

**Comment by portapipe** [comment]
Grazie del consiglio.
In effetti bypassando la versione PHP siamo riusciti ad installarlo.
C'erano alcuni fix da fare in libreria però almeno funziona.
(che poi potrebbero fare anche loro, visto che è poca roba)
Grazie :)
